trigger:
- main # Change this to your main branch

pr:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: '7.x'
      includePreviewVersions: true

  - script: dotnet restore .\api\api.csproj
    displayName: 'Restore dependencies'

  - script: dotnet build .\api\api.csproj --configuration Release
    displayName: 'Build the project'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration Release --collect "Code coverage"'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage results'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/**/*.xml'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Agent.TempDirectory)'
